import { ThemeProvider } from "@mui/material/styles"
import theme from './theme';
import { CssBaseline } from "@mui/material";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link href='https://fonts.googleapis.com/css?family=Poppins' rel='stylesheet' />
        <link href='https://fonts.googleapis.com/css?family=DM Sans' rel='stylesheet' />
      </head>
      <body style={{ margin: 0 }}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          {children}
        </ThemeProvider>
      </body>

    </html>
  )
}
